# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'windows-2019'
variables:
  system.debug: "true"
  solution: '**\*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release' 
  buildArtifactName: drop
stages:
-  stage: Build
   jobs:
   - job: Build     
     steps:
    ###### Dot Net Build to build projects
     - task: UseDotNet@2
       inputs:
        version: '3.0.x'
        packageType: runtime
     - task: DotNetCoreCLI@2
       displayName: 'dotnet restore'
       inputs:
        command: restore
        projects: '**/*.csproj'
     - task: DotNetCoreCLI@2
       displayName: 'dotnet build'
       inputs:
        projects: '**/*.csproj'
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
     - script: |
        echo 'Default Working Directory: $(System.DefaultWorkingDirectory)'
     - script: |
        ls -ltr $(System.DefaultWorkingDirectory)
        
    ### Dot net core publish to copy build to artifact staging directory
     - task: DotNetCoreCLI@2
       inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: False
     - task: CopyFiles@2
       displayName: 'Copy Files'
       inputs:
        SourceFolder: 'HopefulMommaDesignsAPI/HopefulMommaDesignsAPI/AzureResourceGroup'
        Contents: '*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/AzureResourceGroup'
     - task: PublishBuildArtifacts@1
       inputs:
         pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
         artifactName: '$(buildArtifactName)'
- stage: Deploy
  jobs: 
  - deployment: DeployDev
    displayName: Deploy Dev
    pool:
      vmImage: 'vs2017-win2016'
    environment: 'learnk8s-cloud-dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                dir $(Pipeline.Workspace)\$(buildArtifactName)\AzureResourceGroup
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'TransformingDev'
                subscriptionId: '91d5a083-c93b-4df9-b783-478aab256259'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'learnk8s'
                location: 'South Central US'
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/$(buildArtifactName)/AzureResourceGroup/azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)/$(buildArtifactName)/AzureResourceGroup/azuredeploy.parameters-dev.json'
                deploymentMode: 'Incremental'